# Kahani Configuration
# Infrastructure and deployment settings

server:
  backend:
    port: 9876
    host: 0.0.0.0
  
  frontend:
    port: 6789
    # API URL will be auto-detected or use environment variable
    # apiUrl: ${KAHANI_API_URL:-auto}

deployment:
  environment: development
  debug: true

paths:
  data: ./data
  exports: ./exports
  logs: ./logs
