# Kahani Configuration
# Infrastructure and deployment settings

server:
  backend:
    port: 9876
    host: 0.0.0.0
  
  frontend:
    port: 6789
    apiUrl: http://localhost:9876

deployment:
  environment: development
  debug: true

paths:
  data: ./data
  exports: ./exports
  logs: ./logs
