# Docker Compose with Network Configuration
# This example shows how to configure Kahani for different deployment scenarios

version: '3.8'

services:
  kahani-backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "9876:9876"
    environment:
      - KAHANI_ENV=production
      - KAHANI_API_URL=http://localhost:9876
      - KAHANI_FRONTEND_URL=http://localhost:6789
      - KAHANI_CORS_ORIGINS=["http://localhost:6789", "http://localhost:3000"]
      - DOCKER_CONTAINER=true
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - kahani-network

  kahani-frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "6789:6789"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:9876
    depends_on:
      - kahani-backend
    networks:
      - kahani-network

networks:
  kahani-network:
    driver: bridge
