# Docker Compose Development Override
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

version: '3.8'

services:
  kahani-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: builder  # Use builder stage for development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app  # Mount source code for hot reload
      - kahani_data:/app/data
      - kahani_audio:/app/data/audio
      - kahani_logs:/app/logs
    environment:
      - DEBUG=true
      - NODE_ENV=development
      - PYTHONDONTWRITEBYTECODE=1
    ports:
      - "8000:8000"
      - "5678:5678"  # Debugging port

  kahani-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: deps  # Use deps stage for development
    command: npm run dev
    volumes:
      - ./frontend:/app  # Mount source code for hot reload
      - /app/node_modules  # Prevent overwriting node_modules
      - /app/.next  # Prevent overwriting .next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
    ports:
      - "3000:3000"

  # PostgreSQL is optional in dev, comment out if using SQLite
  postgres:
    profiles:
      - with-postgres

  # Development tools
  adminer:
    image: adminer:latest
    container_name: kahani-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DESIGN=nette
    networks:
      - kahani-network
    profiles:
      - with-adminer

volumes:
  kahani_data:
  kahani_audio:
  kahani_logs:
