"""Initial database schema

Revision ID: 001
Revises: 
Create Date: 2025-10-28 10:13:24.959782

Creates all base tables for Kahani application including:
- Users, user settings, and system settings
- Stories, chapters, scenes, and characters
- TTS settings and provider configurations
- Semantic memory and entity state tracking
- Writing style presets and prompt templates
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('allow_nsfw', sa.Boolean(), nullable=False),
    sa.Column('can_change_llm_provider', sa.Boolean(), nullable=False),
    sa.Column('can_change_tts_settings', sa.Boolean(), nullable=False),
    sa.Column('can_use_stt', sa.Boolean(), nullable=False),
    sa.Column('can_use_image_generation', sa.Boolean(), nullable=False),
    sa.Column('can_export_stories', sa.Boolean(), nullable=False),
    sa.Column('can_import_stories', sa.Boolean(), nullable=False),
    sa.Column('max_stories', sa.Integer(), nullable=True),
    sa.Column('max_images_per_story', sa.Integer(), nullable=True),
    sa.Column('max_stt_minutes_per_month', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('personality_traits', sa.JSON(), nullable=True),
    sa.Column('background', sa.Text(), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('fears', sa.Text(), nullable=True),
    sa.Column('appearance', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_characters_id'), ['id'], unique=False)

    op.create_table('prompt_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('user_prompt_template', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_templates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_templates_template_key'), ['template_key'], unique=False)

    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('privacy_level', sa.Enum('PRIVATE', 'FRIENDS', 'UNLISTED', 'PUBLIC', name='privacylevel'), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'ARCHIVED', name='storystatus'), nullable=True),
    sa.Column('story_mode', sa.Enum('DYNAMIC', 'STRUCTURED', name='storymode'), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('tone', sa.String(length=50), nullable=True),
    sa.Column('target_length', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('world_setting', sa.Text(), nullable=True),
    sa.Column('initial_premise', sa.Text(), nullable=True),
    sa.Column('scenario', sa.Text(), nullable=True),
    sa.Column('story_context', sa.JSON(), nullable=True),
    sa.Column('creation_step', sa.Integer(), nullable=True),
    sa.Column('draft_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scene_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stories_id'), ['id'], unique=False)

    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default_allow_nsfw', sa.Boolean(), nullable=False),
    sa.Column('default_can_change_llm_provider', sa.Boolean(), nullable=False),
    sa.Column('default_can_change_tts_settings', sa.Boolean(), nullable=False),
    sa.Column('default_can_use_stt', sa.Boolean(), nullable=False),
    sa.Column('default_can_use_image_generation', sa.Boolean(), nullable=False),
    sa.Column('default_can_export_stories', sa.Boolean(), nullable=False),
    sa.Column('default_can_import_stories', sa.Boolean(), nullable=False),
    sa.Column('default_max_stories', sa.Integer(), nullable=True),
    sa.Column('default_max_images_per_story', sa.Integer(), nullable=True),
    sa.Column('default_max_stt_minutes_per_month', sa.Integer(), nullable=True),
    sa.Column('default_llm_api_url', sa.String(length=500), nullable=True),
    sa.Column('default_llm_api_key', sa.String(length=500), nullable=True),
    sa.Column('default_llm_model_name', sa.String(length=200), nullable=True),
    sa.Column('default_llm_temperature', sa.Float(), nullable=False),
    sa.Column('registration_requires_approval', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_id'), ['id'], unique=False)

    op.create_table('tts_provider_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('api_url', sa.String(length=500), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('voice_id', sa.String(length=100), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('extra_params', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider_type', name='uq_user_provider')
    )
    with op.batch_alter_table('tts_provider_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tts_provider_configs_id'), ['id'], unique=False)

    op.create_table('tts_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tts_enabled', sa.Boolean(), nullable=True),
    sa.Column('tts_provider_type', sa.String(length=50), nullable=True),
    sa.Column('tts_api_url', sa.String(length=500), nullable=True),
    sa.Column('tts_api_key', sa.String(length=500), nullable=True),
    sa.Column('tts_timeout', sa.Integer(), nullable=True),
    sa.Column('tts_retry_attempts', sa.Integer(), nullable=True),
    sa.Column('tts_custom_headers', sa.JSON(), nullable=True),
    sa.Column('tts_extra_params', sa.JSON(), nullable=True),
    sa.Column('default_voice', sa.String(length=100), nullable=True),
    sa.Column('speech_speed', sa.Float(), nullable=True),
    sa.Column('audio_format', sa.String(length=10), nullable=True),
    sa.Column('progressive_narration', sa.Boolean(), nullable=True),
    sa.Column('chunk_size', sa.Integer(), nullable=True),
    sa.Column('stream_audio', sa.Boolean(), nullable=True),
    sa.Column('auto_play_last_scene', sa.Boolean(), nullable=True),
    sa.Column('pause_between_paragraphs', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('tts_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tts_settings_id'), ['id'], unique=False)

    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('llm_temperature', sa.Float(), nullable=True),
    sa.Column('llm_top_p', sa.Float(), nullable=True),
    sa.Column('llm_top_k', sa.Integer(), nullable=True),
    sa.Column('llm_repetition_penalty', sa.Float(), nullable=True),
    sa.Column('llm_max_tokens', sa.Integer(), nullable=True),
    sa.Column('llm_api_url', sa.String(length=500), nullable=True),
    sa.Column('llm_api_key', sa.String(length=500), nullable=True),
    sa.Column('llm_api_type', sa.String(length=50), nullable=True),
    sa.Column('llm_model_name', sa.String(length=200), nullable=True),
    sa.Column('context_max_tokens', sa.Integer(), nullable=True),
    sa.Column('context_keep_recent_scenes', sa.Integer(), nullable=True),
    sa.Column('context_summary_threshold', sa.Integer(), nullable=True),
    sa.Column('context_summary_threshold_tokens', sa.Integer(), nullable=True),
    sa.Column('enable_context_summarization', sa.Boolean(), nullable=True),
    sa.Column('auto_generate_summaries', sa.Boolean(), nullable=True),
    sa.Column('enable_semantic_memory', sa.Boolean(), nullable=True),
    sa.Column('context_strategy', sa.String(length=20), nullable=True),
    sa.Column('semantic_search_top_k', sa.Integer(), nullable=True),
    sa.Column('semantic_scenes_in_context', sa.Integer(), nullable=True),
    sa.Column('semantic_context_weight', sa.Float(), nullable=True),
    sa.Column('character_moments_in_context', sa.Integer(), nullable=True),
    sa.Column('auto_extract_character_moments', sa.Boolean(), nullable=True),
    sa.Column('auto_extract_plot_events', sa.Boolean(), nullable=True),
    sa.Column('extraction_confidence_threshold', sa.Integer(), nullable=True),
    sa.Column('default_genre', sa.String(length=100), nullable=True),
    sa.Column('default_tone', sa.String(length=100), nullable=True),
    sa.Column('preferred_scene_length', sa.String(length=50), nullable=True),
    sa.Column('enable_auto_choices', sa.Boolean(), nullable=True),
    sa.Column('choices_count', sa.Integer(), nullable=True),
    sa.Column('color_theme', sa.String(length=30), nullable=True),
    sa.Column('font_size', sa.String(length=20), nullable=True),
    sa.Column('show_token_info', sa.Boolean(), nullable=True),
    sa.Column('show_context_info', sa.Boolean(), nullable=True),
    sa.Column('enable_notifications', sa.Boolean(), nullable=True),
    sa.Column('scene_display_format', sa.String(length=20), nullable=True),
    sa.Column('show_scene_titles', sa.Boolean(), nullable=True),
    sa.Column('auto_open_last_story', sa.Boolean(), nullable=True),
    sa.Column('last_accessed_story_id', sa.Integer(), nullable=True),
    sa.Column('default_export_format', sa.String(length=20), nullable=True),
    sa.Column('include_metadata', sa.Boolean(), nullable=True),
    sa.Column('include_choices', sa.Boolean(), nullable=True),
    sa.Column('enable_character_suggestions', sa.Boolean(), nullable=True),
    sa.Column('character_importance_threshold', sa.Integer(), nullable=True),
    sa.Column('character_mention_threshold', sa.Integer(), nullable=True),
    sa.Column('custom_system_prompt', sa.Text(), nullable=True),
    sa.Column('enable_experimental_features', sa.Boolean(), nullable=True),
    sa.Column('engine_settings', sa.Text(), nullable=True),
    sa.Column('current_engine', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_settings_id'), ['id'], unique=False)

    op.create_table('writing_style_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('summary_system_prompt', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('writing_style_presets', schema=None) as batch_op:
        batch_op.create_index('idx_writing_presets_user_active', ['user_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_writing_style_presets_id'), ['id'], unique=False)

    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plot_point', sa.Text(), nullable=True),
    sa.Column('plot_point_index', sa.Integer(), nullable=True),
    sa.Column('story_so_far', sa.Text(), nullable=True),
    sa.Column('auto_summary', sa.Text(), nullable=True),
    sa.Column('last_summary_scene_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', name='chapterstatus'), nullable=True),
    sa.Column('context_tokens_used', sa.Integer(), nullable=True),
    sa.Column('scenes_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapters_id'), ['id'], unique=False)

    op.create_table('character_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('last_updated_scene', sa.Integer(), nullable=True),
    sa.Column('current_location', sa.Text(), nullable=True),
    sa.Column('physical_condition', sa.Text(), nullable=True),
    sa.Column('appearance', sa.Text(), nullable=True),
    sa.Column('possessions', sa.JSON(), nullable=True),
    sa.Column('emotional_state', sa.Text(), nullable=True),
    sa.Column('current_goal', sa.Text(), nullable=True),
    sa.Column('active_conflicts', sa.JSON(), nullable=True),
    sa.Column('knowledge', sa.JSON(), nullable=True),
    sa.Column('secrets', sa.JSON(), nullable=True),
    sa.Column('relationships', sa.JSON(), nullable=True),
    sa.Column('arc_stage', sa.Text(), nullable=True),
    sa.Column('arc_progress', sa.Float(), nullable=True),
    sa.Column('recent_decisions', sa.JSON(), nullable=True),
    sa.Column('recent_actions', sa.JSON(), nullable=True),
    sa.Column('full_state', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_states_id'), ['id'], unique=False)

    op.create_table('location_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('last_updated_scene', sa.Integer(), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('atmosphere', sa.Text(), nullable=True),
    sa.Column('notable_features', sa.JSON(), nullable=True),
    sa.Column('current_occupants', sa.JSON(), nullable=True),
    sa.Column('significant_events', sa.JSON(), nullable=True),
    sa.Column('time_of_day', sa.String(length=50), nullable=True),
    sa.Column('weather', sa.String(length=255), nullable=True),
    sa.Column('full_state', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_states_id'), ['id'], unique=False)

    op.create_table('object_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('object_name', sa.String(length=255), nullable=False),
    sa.Column('last_updated_scene', sa.Integer(), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('current_location', sa.Text(), nullable=True),
    sa.Column('current_owner_id', sa.Integer(), nullable=True),
    sa.Column('significance', sa.Text(), nullable=True),
    sa.Column('object_type', sa.String(length=100), nullable=True),
    sa.Column('powers', sa.JSON(), nullable=True),
    sa.Column('limitations', sa.JSON(), nullable=True),
    sa.Column('origin', sa.Text(), nullable=True),
    sa.Column('previous_owners', sa.JSON(), nullable=True),
    sa.Column('recent_events', sa.JSON(), nullable=True),
    sa.Column('full_state', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['current_owner_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('object_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_object_states_id'), ['id'], unique=False)

    op.create_table('story_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('current_location', sa.String(length=200), nullable=True),
    sa.Column('current_emotional_state', sa.String(length=100), nullable=True),
    sa.Column('current_goals', sa.Text(), nullable=True),
    sa.Column('knowledge_state', sa.JSON(), nullable=True),
    sa.Column('relationships', sa.JSON(), nullable=True),
    sa.Column('character_development', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('introduced_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_appearance', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('story_characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_characters_id'), ['id'], unique=False)

    op.create_table('scenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('parent_scene_id', sa.Integer(), nullable=True),
    sa.Column('branch_choice', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('scene_type', sa.Enum('NARRATIVE', 'DIALOGUE', 'ACTION', 'DESCRIPTION', name='scenetype'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deletion_point', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['parent_scene_id'], ['scenes.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenes_id'), ['id'], unique=False)

    op.create_table('character_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('moment_type', sa.Enum('ACTION', 'DIALOGUE', 'DEVELOPMENT', 'RELATIONSHIP', name='momenttype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_id', sa.String(length=200), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('extracted_automatically', sa.Boolean(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character_memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_memories_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_memories_embedding_id'), ['embedding_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_character_memories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_memories_moment_type'), ['moment_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_memories_scene_id'), ['scene_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_memories_sequence_order'), ['sequence_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_memories_story_id'), ['story_id'], unique=False)

    op.create_table('plot_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('INTRODUCTION', 'COMPLICATION', 'REVELATION', 'RESOLUTION', name='eventtype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('embedding_id', sa.String(length=200), nullable=False),
    sa.Column('thread_id', sa.String(length=100), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('resolution_scene_id', sa.Integer(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('involved_characters', sa.JSON(), nullable=True),
    sa.Column('extracted_automatically', sa.Boolean(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('importance_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolution_scene_id'], ['scenes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plot_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plot_events_embedding_id'), ['embedding_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_plot_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_plot_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plot_events_is_resolved'), ['is_resolved'], unique=False)
        batch_op.create_index(batch_op.f('ix_plot_events_scene_id'), ['scene_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plot_events_sequence_order'), ['sequence_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_plot_events_story_id'), ['story_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plot_events_thread_id'), ['thread_id'], unique=False)

    op.create_table('scene_audio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('audio_url', sa.String(length=500), nullable=False),
    sa.Column('audio_format', sa.String(length=10), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('voice_used', sa.String(length=100), nullable=True),
    sa.Column('speed_used', sa.Float(), nullable=True),
    sa.Column('provider_used', sa.String(length=50), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scene_audio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scene_audio_id'), ['id'], unique=False)

    op.create_table('scene_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('variant_number', sa.Integer(), nullable=False),
    sa.Column('is_original', sa.Boolean(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('characters_present', sa.JSON(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('mood', sa.String(length=100), nullable=True),
    sa.Column('scene_context', sa.JSON(), nullable=True),
    sa.Column('generation_prompt', sa.Text(), nullable=True),
    sa.Column('generation_method', sa.String(length=50), nullable=True),
    sa.Column('original_content', sa.Text(), nullable=True),
    sa.Column('user_edited', sa.Boolean(), nullable=True),
    sa.Column('edit_history', sa.JSON(), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scene_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scene_variants_id'), ['id'], unique=False)

    op.create_table('scene_choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('scene_variant_id', sa.Integer(), nullable=True),
    sa.Column('choice_text', sa.Text(), nullable=False),
    sa.Column('choice_description', sa.Text(), nullable=True),
    sa.Column('choice_order', sa.Integer(), nullable=True),
    sa.Column('is_user_created', sa.Boolean(), nullable=True),
    sa.Column('predicted_outcomes', sa.JSON(), nullable=True),
    sa.Column('character_reactions', sa.JSON(), nullable=True),
    sa.Column('times_selected', sa.Integer(), nullable=True),
    sa.Column('leads_to_scene_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['leads_to_scene_id'], ['scenes.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.ForeignKeyConstraint(['scene_variant_id'], ['scene_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scene_choices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scene_choices_id'), ['id'], unique=False)

    op.create_table('scene_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('embedding_id', sa.String(length=200), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('embedding_version', sa.String(length=20), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['scene_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scene_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scene_embeddings_embedding_id'), ['embedding_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_scene_embeddings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scene_embeddings_scene_id'), ['scene_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scene_embeddings_sequence_order'), ['sequence_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_scene_embeddings_story_id'), ['story_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scene_embeddings_variant_id'), ['variant_id'], unique=False)

    op.create_table('story_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('scene_variant_id', sa.Integer(), nullable=False),
    sa.Column('from_choice_id', sa.Integer(), nullable=True),
    sa.Column('choice_text', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('flow_name', sa.String(length=100), nullable=True),
    sa.Column('created_by_session', sa.String(length=100), nullable=True),
    sa.Column('last_accessed', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['from_choice_id'], ['scene_choices.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.ForeignKeyConstraint(['scene_variant_id'], ['scene_variants.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('story_flows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_flows_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story_flows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_flows_id'))

    op.drop_table('story_flows')
    with op.batch_alter_table('scene_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scene_embeddings_variant_id'))
        batch_op.drop_index(batch_op.f('ix_scene_embeddings_story_id'))
        batch_op.drop_index(batch_op.f('ix_scene_embeddings_sequence_order'))
        batch_op.drop_index(batch_op.f('ix_scene_embeddings_scene_id'))
        batch_op.drop_index(batch_op.f('ix_scene_embeddings_id'))
        batch_op.drop_index(batch_op.f('ix_scene_embeddings_embedding_id'))

    op.drop_table('scene_embeddings')
    with op.batch_alter_table('scene_choices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scene_choices_id'))

    op.drop_table('scene_choices')
    with op.batch_alter_table('scene_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scene_variants_id'))

    op.drop_table('scene_variants')
    with op.batch_alter_table('scene_audio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scene_audio_id'))

    op.drop_table('scene_audio')
    with op.batch_alter_table('plot_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plot_events_thread_id'))
        batch_op.drop_index(batch_op.f('ix_plot_events_story_id'))
        batch_op.drop_index(batch_op.f('ix_plot_events_sequence_order'))
        batch_op.drop_index(batch_op.f('ix_plot_events_scene_id'))
        batch_op.drop_index(batch_op.f('ix_plot_events_is_resolved'))
        batch_op.drop_index(batch_op.f('ix_plot_events_id'))
        batch_op.drop_index(batch_op.f('ix_plot_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_plot_events_embedding_id'))

    op.drop_table('plot_events')
    with op.batch_alter_table('character_memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_memories_story_id'))
        batch_op.drop_index(batch_op.f('ix_character_memories_sequence_order'))
        batch_op.drop_index(batch_op.f('ix_character_memories_scene_id'))
        batch_op.drop_index(batch_op.f('ix_character_memories_moment_type'))
        batch_op.drop_index(batch_op.f('ix_character_memories_id'))
        batch_op.drop_index(batch_op.f('ix_character_memories_embedding_id'))
        batch_op.drop_index(batch_op.f('ix_character_memories_character_id'))

    op.drop_table('character_memories')
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenes_id'))

    op.drop_table('scenes')
    with op.batch_alter_table('story_characters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_characters_id'))

    op.drop_table('story_characters')
    with op.batch_alter_table('object_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_object_states_id'))

    op.drop_table('object_states')
    with op.batch_alter_table('location_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_states_id'))

    op.drop_table('location_states')
    with op.batch_alter_table('character_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_states_id'))

    op.drop_table('character_states')
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapters_id'))

    op.drop_table('chapters')
    with op.batch_alter_table('writing_style_presets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_writing_style_presets_id'))
        batch_op.drop_index('idx_writing_presets_user_active')

    op.drop_table('writing_style_presets')
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_settings_id'))

    op.drop_table('user_settings')
    with op.batch_alter_table('tts_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tts_settings_id'))

    op.drop_table('tts_settings')
    with op.batch_alter_table('tts_provider_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tts_provider_configs_id'))

    op.drop_table('tts_provider_configs')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_id'))

    op.drop_table('system_settings')
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stories_id'))

    op.drop_table('stories')
    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_templates_template_key'))
        batch_op.drop_index(batch_op.f('ix_prompt_templates_id'))

    op.drop_table('prompt_templates')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_characters_id'))

    op.drop_table('characters')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
