"""Add user settings table

Revision ID: add_user_settings
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'add_user_settings'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('llm_temperature', sa.Float(), nullable=True),
    sa.Column('llm_top_p', sa.Float(), nullable=True),
    sa.Column('llm_top_k', sa.Integer(), nullable=True),
    sa.Column('llm_repetition_penalty', sa.Float(), nullable=True),
    sa.Column('llm_max_tokens', sa.Integer(), nullable=True),
    sa.Column('context_max_tokens', sa.Integer(), nullable=True),
    sa.Column('context_keep_recent_scenes', sa.Integer(), nullable=True),
    sa.Column('context_summary_threshold', sa.Integer(), nullable=True),
    sa.Column('context_enable_summarization', sa.Boolean(), nullable=True),
    sa.Column('generation_default_genre', sa.String(length=100), nullable=True),
    sa.Column('generation_default_tone', sa.String(length=100), nullable=True),
    sa.Column('generation_scene_length', sa.String(length=20), nullable=True),
    sa.Column('generation_auto_choices', sa.Boolean(), nullable=True),
    sa.Column('generation_choices_count', sa.Integer(), nullable=True),
    sa.Column('ui_theme', sa.String(length=20), nullable=True),
    sa.Column('ui_font_size', sa.String(length=20), nullable=True),
    sa.Column('ui_show_token_info', sa.Boolean(), nullable=True),
    sa.Column('ui_show_context_info', sa.Boolean(), nullable=True),
    sa.Column('ui_notifications', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    # ### end Alembic commands ###