"""add scenario field to stories

Revision ID: 004_add_scenario_field_to_stories
Revises: 003_add_admin_system
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004_add_scenario_field_to_stories'
down_revision = '003_add_admin_system'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('scenario', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'scenario')
    # ### end Alembic commands ###
